### ISSUE TITLE
Getting syntax error when running gen_report.js

### ISSUE THREAD

**Issue by plermant** [samccone/coverage-ext#10]
Hi - I've been looking for a tool like so i was excited to try it out. All the steps went fine, except for the report generation. For some reason I am getting an error. I checked the ycombinator-data json and it looks fine, so it could be due to my particular setup. I run Ubuntu 14.04 under VmWare for Windows..:

**Failing command:**
plermant@ubuntu:/mnt/hgfs/desktopBin/coverage-ext-master/reporter$ nodejs gen_report.js ../ycombinator-data

/mnt/hgfs/desktopBin/coverage-ext-master/reporter/gen_report.js:39
Object.keys(originals).forEach(key => {
                                    ^
SyntaxError: Unexpected token >
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:902:3

**ycombinator-data file (shortened ...)**
plermant@ubuntu:/mnt/hgfs/desktopBin/coverage-ext-master$ cat ycombinator-data | more
{
  "coverage": "{\"https---news-ycombinator-com-hn-js-X1iBjkGcTj5LvmbPKLg4---0.7274\":{\"path\":\"https---news-ycombinator-com-hn-js-X1iBjkGc
Tj5LvmbPKLg4---0.7274\",\"s\ ......(cut)

**Comment by samccone** [comment]
@plermant I'm guessing you are using node 12? Update your node version and you should be good

**Comment by plermant** [comment]
Sam, you were correct, I updated to latest nodejs (v6.6.0) and it's working as expected. I also had to run the npm instal with the flag "--no-bin-links" in case anyone else sees issues with this.Thanks a bunch

Pierre

**Comment by samccone** [comment]
Glad you got it 😁
