### ISSUE TITLE
gen_report creates broken links

### ISSUE THREAD

**Issue by s3ththompson** [samccone/coverage-ext#3]
gen_report is creating files called `index.html.html` which yield broken reports.

**Comment by chchrist** [comment]
I have the same issue

**Comment by samccone** [comment]
Sorry about this, please try now.

**Comment by s3ththompson** [comment]
you're fast. beat me to it https://github.com/s3ththompson/coverage-ext/commit/72f822619596330d4c5e6a24c6c10e5862ac6e8c
